{% set name = "r-essentials" %}

package:
  name: {{ name }}
  version: {{ r_base }}

build:
  noarch: generic
  # r-rbokeh is not available under Windows
  number: 2001

requirements:
    host:
        - r-base
    run:
        - r-base
        - r-recommended {{ version }}
        - r-ggplot2 >=3.1.0
        - r-plyr >=1.8.4
        - r-reshape2 >=1.4.3
        - r-dplyr >=0.7.8
        - r-tidyr >=0.8.1
        - r-caret >=6.0_80
        - r-randomforest >=4.6_14
        - r-data.table >=1.11.8
        - r-quantmod >=0.4_13
        - r-shiny >=1.2.0
        - r-rmarkdown >=1.10
        - r-glmnet >=2.0_16
        - r-jsonlite >=1.5
        - r-zoo >=1.8_3
        - r-irkernel >=0.8.14
        - r-rbokeh >=0.5.0
        - r-formatr >=1.5
        - notebook >=5.7.2
        - r-tidyverse >=1.2.1
        - r-dbi >=1.0.0
        - r-broom >=0.5.0
        - r-forcats >=0.3.0
        - r-haven >=1.1.2
        - r-hms >=0.4.2
        - r-httr >=1.3.1
        - r-lubridate >=1.7.4
        - r-magrittr >=1.5
        - r-modelr >=0.1.2
        - r-purrr >=0.2.5
        - r-readr >=1.1.1
        - r-readxl >=1.1.0
        - r-rvest >=0.3.2
        - r-stringr >=1.3.1
        - r-tibble >=1.4.2
        - r-xml2 >=1.2.0

test:
  commands:
    - $R -e "library('ggplot2')"  # [not win]
    - $R -e "library('tibble')"  # [not win]
    - "\"%R%\" -e \"library('ggplot2')\""  # [win]
    - "\"%R%\" -e \"library('tibble')\""  # [win]

about:
    home: https://github.com/conda-forge/r-essentials-feedstock
    license: Various
    license_family: Other
    summary: Some essential packages for working with R. This was migrated from the 'r' channel.

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
