travis:
  secure:
    BINSTAR_TOKEN: WZOVtpBBVzXzS52lGYV6NJ88W9eKHcXSajG0MRPLV+mCoJmtP3k+r6UPd85R1nDLNbaHc+4G3gFNcLSxjZ2aGb9TsVDWCTc510UIx6jMqncqR7NpF6EEyMRIgMBpOS2eX9/5NKlamkf/QtJY7MLKNxv+GehM6MS96LzwlkdNIWT9djyKW6cI/95m1xGp6+HUn2T8OhxTCnu421i0qD121I+jjVcTy1I010bnBc/3fOCG9domeCXVxce8e5nAx7dqKRXDkTYtSDg3feLnqtRuzuONZa9HIT2JpMYblJlmAlkGr1WKoiV1xTFD31+K5D7NU0t0F/siRfrxBsreQldReM2iqjZTJPfy7rLDWxWKOb+x1u/tWzoAJ/p4bHvldfDEG4bi9+ta77ZIX24qcsr0MIQ4e+cByQL9SURqo1bx3UeQFCa/94bj0jrLY0nqRtHXNsgLVKcDI124p0fwOlC58CvPhEIjIBXWvd3JIOzLysfGtBVZe7MNHlTfFBjxrhUgxMmcWEy7fejlHoRFl9hk66GWyQy8S52CDRn5PSFsRSndbwDN+w9NhOvhKBRyLwjcPFi9LrYpS5W4FIYVJ0H7PUGXsX++8xo2e8lARHM0Wmx0B4MwFc0VCrd7RfxjHidypu7CFmrg3X6W6ssS0Tp1ZyTDmk7siud8lAZl43aVv18=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
